eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    


microservice:
  restaurant-service:
    endpoints:
      endpoint:
        uri:http://RESTAURANT-SERVICE/api/v1/restaurants/restaurant/menuItems/
  order-service:
    endpoints:
      endpoint:
        uri:http://ORDER-SERVICE/api/v1/orders/getAmount/
